name: Deploy Java App

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: deploy
        run: echo "${{ secrets.DEPLOY }}" | base64 -d > .env